/**
       GRUPO
       
    André Prado Arantes 
    Claudio 
    Yuri 
    
 */
package View;

import Controller.ctrPrincipal;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    ctrPrincipal objPrincipal;
    
    public TelaPrincipal(ctrPrincipal pCtr) {
        objPrincipal = pCtr;
        this.setVisible(true);
        initComponents();
    }
    
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaPrincipal = new javax.swing.JPanel();
        TelaDefault = new javax.swing.JPanel();
        CadastroImovel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        BuscaImovel = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        CadastroVenda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodImovel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNomeComprador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonConfirma1 = new javax.swing.JButton();
        jButtonCancela1 = new javax.swing.JButton();
        jTextFieldCorretorResponsavel = new javax.swing.JTextField();
        jTextFieldValorVenda = new javax.swing.JTextField();
        jTextFieldDataVenda = new javax.swing.JFormattedTextField();
        CadastroCorretorCT = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNameCT = new javax.swing.JTextField();
        jTextFieldNumberCT = new javax.swing.JTextField();
        jTextFieldSalCT = new javax.swing.JTextField();
        jTextField1DataCT = new javax.swing.JFormattedTextField();
        jButtonCancela2 = new javax.swing.JButton();
        jButtonConfirma2 = new javax.swing.JButton();
        CadastroCorretorCM = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButtonCancela3 = new javax.swing.JButton();
        jButtonConfirma3 = new javax.swing.JButton();
        jTextFieldNameCM = new javax.swing.JTextField();
        jTextFieldNumberCM = new javax.swing.JTextField();
        jComboBoxComissao = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuBusca = new javax.swing.JMenu();
        jMenuBuscaImovel = new javax.swing.JMenuItem();
        jMenuCadastroImovel = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuCadastroVenda = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuCadastroCorretorCT = new javax.swing.JMenuItem();
        jMenuCadastroCorretorCM = new javax.swing.JMenuItem();
        jMenuSalario_Comissao = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuRelátorios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TelaPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout TelaDefaultLayout = new javax.swing.GroupLayout(TelaDefault);
        TelaDefault.setLayout(TelaDefaultLayout);
        TelaDefaultLayout.setHorizontalGroup(
            TelaDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        TelaDefaultLayout.setVerticalGroup(
            TelaDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        TelaPrincipal.add(TelaDefault, "TelaDefault");

        jLabel6.setText("jLabel6");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout CadastroImovelLayout = new javax.swing.GroupLayout(CadastroImovel);
        CadastroImovel.setLayout(CadastroImovelLayout);
        CadastroImovelLayout.setHorizontalGroup(
            CadastroImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroImovelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(534, Short.MAX_VALUE))
        );
        CadastroImovelLayout.setVerticalGroup(
            CadastroImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroImovelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(382, Short.MAX_VALUE))
        );

        TelaPrincipal.add(CadastroImovel, "TelaCadastroImovel");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("jButton1");

        javax.swing.GroupLayout BuscaImovelLayout = new javax.swing.GroupLayout(BuscaImovel);
        BuscaImovel.setLayout(BuscaImovelLayout);
        BuscaImovelLayout.setHorizontalGroup(
            BuscaImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaImovelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, 565, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        BuscaImovelLayout.setVerticalGroup(
            BuscaImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaImovelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscaImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(374, Short.MAX_VALUE))
        );

        TelaPrincipal.add(BuscaImovel, "TelaBusca");

        jLabel1.setText("Código do Imóvel:");

        jLabel2.setText("Valor da Venda:");

        jLabel3.setText("Nome do Comprador:");

        jLabel4.setText("Data:");

        jLabel5.setText("Corretor Responsável:");

        jButtonConfirma1.setText("Confirma");
        jButtonConfirma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirma1ActionPerformed(evt);
            }
        });

        jButtonCancela1.setText("Cancela");
        jButtonCancela1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancela1ActionPerformed(evt);
            }
        });

        try {
            jTextFieldDataVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout CadastroVendaLayout = new javax.swing.GroupLayout(CadastroVenda);
        CadastroVenda.setLayout(CadastroVendaLayout);
        CadastroVendaLayout.setHorizontalGroup(
            CadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroVendaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodImovel))
                    .addGroup(CadastroVendaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCorretorResponsavel))
                    .addGroup(CadastroVendaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorVenda))
                    .addGroup(CadastroVendaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeComprador))
                    .addGroup(CadastroVendaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDataVenda))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroVendaLayout.createSequentialGroup()
                        .addGap(0, 466, Short.MAX_VALUE)
                        .addComponent(jButtonConfirma1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancela1)))
                .addContainerGap())
        );

        CadastroVendaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        CadastroVendaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancela1, jButtonConfirma1});

        CadastroVendaLayout.setVerticalGroup(
            CadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCodImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNomeComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldCorretorResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addGroup(CadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirma1)
                    .addComponent(jButtonCancela1))
                .addContainerGap())
        );

        TelaPrincipal.add(CadastroVenda, "TelaCadastroVenda");

        jLabel7.setText("Nome:");

        jLabel8.setText("Nº CRECI:");

        jLabel9.setText("Salário Fixo:");

        jLabel10.setText("Data de Admissão:");

        jTextFieldSalCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalCTActionPerformed(evt);
            }
        });

        try {
            jTextField1DataCT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButtonCancela2.setText("Cancela");
        jButtonCancela2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancela2ActionPerformed(evt);
            }
        });

        jButtonConfirma2.setText("Confirma");
        jButtonConfirma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirma2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CadastroCorretorCTLayout = new javax.swing.GroupLayout(CadastroCorretorCT);
        CadastroCorretorCT.setLayout(CadastroCorretorCTLayout);
        CadastroCorretorCTLayout.setHorizontalGroup(
            CadastroCorretorCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroCorretorCTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroCorretorCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroCorretorCTLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1DataCT))
                    .addGroup(CadastroCorretorCTLayout.createSequentialGroup()
                        .addGroup(CadastroCorretorCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastroCorretorCTLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNameCT, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CadastroCorretorCTLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNumberCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CadastroCorretorCTLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSalCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroCorretorCTLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonConfirma2)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancela2)))
                .addContainerGap())
        );

        CadastroCorretorCTLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel7, jLabel8, jLabel9});

        CadastroCorretorCTLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldNameCT, jTextFieldNumberCT, jTextFieldSalCT});

        CadastroCorretorCTLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancela2, jButtonConfirma2});

        CadastroCorretorCTLayout.setVerticalGroup(
            CadastroCorretorCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroCorretorCTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroCorretorCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldNameCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroCorretorCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldNumberCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroCorretorCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldSalCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroCorretorCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField1DataCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addGroup(CadastroCorretorCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancela2)
                    .addComponent(jButtonConfirma2))
                .addContainerGap())
        );

        TelaPrincipal.add(CadastroCorretorCT, "TelaCadastroCT");

        jLabel11.setText("Nome:");

        jLabel12.setText("Nº CRECI");

        jLabel13.setText("Comissão (%) :");

        jButtonCancela3.setText("Cancela");
        jButtonCancela3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancela3ActionPerformed(evt);
            }
        });

        jButtonConfirma3.setText("Confirma");
        jButtonConfirma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirma3ActionPerformed(evt);
            }
        });

        jComboBoxComissao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        javax.swing.GroupLayout CadastroCorretorCMLayout = new javax.swing.GroupLayout(CadastroCorretorCM);
        CadastroCorretorCM.setLayout(CadastroCorretorCMLayout);
        CadastroCorretorCMLayout.setHorizontalGroup(
            CadastroCorretorCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroCorretorCMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroCorretorCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroCorretorCMLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonConfirma3)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancela3))
                    .addGroup(CadastroCorretorCMLayout.createSequentialGroup()
                        .addGroup(CadastroCorretorCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastroCorretorCMLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNameCM, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CadastroCorretorCMLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNumberCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CadastroCorretorCMLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        CadastroCorretorCMLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel12, jLabel13});

        CadastroCorretorCMLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldNameCM, jTextFieldNumberCM});

        CadastroCorretorCMLayout.setVerticalGroup(
            CadastroCorretorCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroCorretorCMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroCorretorCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldNameCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroCorretorCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldNumberCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroCorretorCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addGroup(CadastroCorretorCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancela3)
                    .addComponent(jButtonConfirma3))
                .addContainerGap())
        );

        TelaPrincipal.add(CadastroCorretorCM, "TelaCadastroCM");

        jMenuBusca.setText("Imóveis");

        jMenuBuscaImovel.setText("Busca");
        jMenuBuscaImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscaImovelActionPerformed(evt);
            }
        });
        jMenuBusca.add(jMenuBuscaImovel);

        jMenuCadastroImovel.setText("Cadastro");
        jMenuCadastroImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroImovelActionPerformed(evt);
            }
        });
        jMenuBusca.add(jMenuCadastroImovel);

        jMenuBar1.add(jMenuBusca);

        jMenu2.setText("Vendas");

        jMenuCadastroVenda.setText("Cadastro");
        jMenuCadastroVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroVendaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuCadastroVenda);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Corretores");

        jMenu1.setText("Cadastro");

        jMenuCadastroCorretorCT.setText("Contratado");
        jMenuCadastroCorretorCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroCorretorCTActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastroCorretorCT);

        jMenuCadastroCorretorCM.setText("Comissionado");
        jMenuCadastroCorretorCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroCorretorCMActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastroCorretorCM);

        jMenu3.add(jMenu1);

        jMenuSalario_Comissao.setText("Salários / Comissões");
        jMenu3.add(jMenuSalario_Comissao);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Outros");

        jMenuRelátorios.setText("Relátorios");
        jMenu4.add(jMenuRelátorios);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(676, 474));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadastroVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroVendaActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal,"TelaCadastroVenda");
    }//GEN-LAST:event_jMenuCadastroVendaActionPerformed

    private void jMenuCadastroImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroImovelActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal,"TelaCadastroImovel");
    }//GEN-LAST:event_jMenuCadastroImovelActionPerformed

    private void jMenuBuscaImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscaImovelActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal,"TelaBusca");
    }//GEN-LAST:event_jMenuBuscaImovelActionPerformed

    private void jButtonConfirma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirma1ActionPerformed
        // TODO add your handling code here:
        String cod = jTextFieldCodImovel.getText();
        float valor = Float.parseFloat(jTextFieldValorVenda.getText());
        String nomeComprador = jTextFieldNomeComprador.getText();
        String data = jTextFieldDataVenda.getText();
        String corretor = jTextFieldCorretorResponsavel.getText();
        
        try {
            objPrincipal.cadVenda(cod,valor,nomeComprador,data,corretor);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        
        jTextFieldCodImovel.setText("");
        jTextFieldValorVenda.setText("");
        jTextFieldNomeComprador.setText("");
        jTextFieldDataVenda.setText("");
        jTextFieldCorretorResponsavel.setText("");
        
        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal,"TelaCadastroVenda");
    }//GEN-LAST:event_jButtonConfirma1ActionPerformed

    private void jButtonCancela1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancela1ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal,"TelaDefault");
    }//GEN-LAST:event_jButtonCancela1ActionPerformed

    private void jTextFieldSalCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalCTActionPerformed

    private void jButtonConfirma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirma2ActionPerformed
        // TODO add your handling code here:
        String name = jTextFieldNameCT.getText();
        String nCRECI = jTextFieldNumberCT.getText();
        float salario = Float.parseFloat(jTextFieldSalCT.getText());
        String data = jTextField1DataCT.getText();
        
        
    }//GEN-LAST:event_jButtonConfirma2ActionPerformed

    private void jButtonCancela2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancela2ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal,"TelaDefault");
    }//GEN-LAST:event_jButtonCancela2ActionPerformed

    private void jButtonCancela3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancela3ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal,"TelaDefault");
    }//GEN-LAST:event_jButtonCancela3ActionPerformed

    private void jButtonConfirma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirma3ActionPerformed
        // TODO add your handling code here:
        String name = jTextFieldNameCM.getText();
        String nCRECI = jTextFieldNumberCM.getText();
        float comission = (1 + (jComboBoxComissao.getSelectedIndex())) / 100;
        
        
    }//GEN-LAST:event_jButtonConfirma3ActionPerformed

    private void jMenuCadastroCorretorCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroCorretorCTActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal,"TelaCadastroCT");
    }//GEN-LAST:event_jMenuCadastroCorretorCTActionPerformed

    private void jMenuCadastroCorretorCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroCorretorCMActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal,"TelaCadastroCM");
    }//GEN-LAST:event_jMenuCadastroCorretorCMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BuscaImovel;
    private javax.swing.JPanel CadastroCorretorCM;
    private javax.swing.JPanel CadastroCorretorCT;
    private javax.swing.JPanel CadastroImovel;
    private javax.swing.JPanel CadastroVenda;
    private javax.swing.JPanel TelaDefault;
    private javax.swing.JPanel TelaPrincipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancela1;
    private javax.swing.JButton jButtonCancela2;
    private javax.swing.JButton jButtonCancela3;
    private javax.swing.JButton jButtonConfirma1;
    private javax.swing.JButton jButtonConfirma2;
    private javax.swing.JButton jButtonConfirma3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxComissao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBusca;
    private javax.swing.JMenuItem jMenuBuscaImovel;
    private javax.swing.JMenuItem jMenuCadastroCorretorCM;
    private javax.swing.JMenuItem jMenuCadastroCorretorCT;
    private javax.swing.JMenuItem jMenuCadastroImovel;
    private javax.swing.JMenuItem jMenuCadastroVenda;
    private javax.swing.JMenuItem jMenuRelátorios;
    private javax.swing.JMenuItem jMenuSalario_Comissao;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JFormattedTextField jTextField1DataCT;
    private javax.swing.JTextField jTextFieldCodImovel;
    private javax.swing.JTextField jTextFieldCorretorResponsavel;
    private javax.swing.JFormattedTextField jTextFieldDataVenda;
    private javax.swing.JTextField jTextFieldNameCM;
    private javax.swing.JTextField jTextFieldNameCT;
    private javax.swing.JTextField jTextFieldNomeComprador;
    private javax.swing.JTextField jTextFieldNumberCM;
    private javax.swing.JTextField jTextFieldNumberCT;
    private javax.swing.JTextField jTextFieldSalCT;
    private javax.swing.JTextField jTextFieldValorVenda;
    // End of variables declaration//GEN-END:variables
}
