/**
 * GRUPO
 *
 * ANDRE PRADO ARANTES - 2016011733
 * CLAUDIO EDUARDO MACHADO SERPA - 2016010683
 * YURI DE PAULA OLIVEIRA - 2016000121
 */
package View;

import Controller.ctrPrincipal;
import Model.Comissionado;
import Model.Contratado;
import Model.Corretor;
import Model.Imovel;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    ctrPrincipal objPrincipal;
    Vector<Corretor> corretores;
    Vector<Imovel> imoveis;

    public TelaPrincipal(ctrPrincipal pCtr) {
        objPrincipal = pCtr;
        corretores = objPrincipal.getObjACtrCorretor().getListaCorretor();
        imoveis = objPrincipal.getObjCtrImovel().getListagemImovel();
        this.setVisible(true);
        initComponents();
    }

    public TelaPrincipal() {
        initComponents();
    }

    public boolean validaDataSalario(String pMes, String pAno) {

        if (pMes.equalsIgnoreCase("") || pAno.equalsIgnoreCase("")) {
            return false;
        } else {

            int mes = Integer.parseInt(pMes);
            int ano = Integer.parseInt(pAno);
            Date dataAtual = new Date();

            GregorianCalendar gc = new GregorianCalendar();
            gc.setTime(dataAtual);
            int year = gc.get(GregorianCalendar.YEAR);

            if (mes > 12 || mes < 1 || ano > year) {
                return false;
            }
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaPrincipal = new javax.swing.JPanel();
        TelaDefault = new javax.swing.JPanel();
        CadastroImovel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldNomeProprietario = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        jTextFieldValor = new javax.swing.JTextField();
        jButtonCadastraImovel = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jComboBoxTipoImovel = new javax.swing.JComboBox<>();
        BuscaImovel = new javax.swing.JPanel();
        jComboBoxTipoImoveis = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableImóveis = new javax.swing.JTable();
        jButtonExcluiImovel = new javax.swing.JButton();
        jButtonEditaImovel = new javax.swing.JButton();
        CadastroVenda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodImovel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNomeComprador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonConfirma1 = new javax.swing.JButton();
        jButtonCancela1 = new javax.swing.JButton();
        jTextFieldValorVenda = new javax.swing.JTextField();
        jTextFieldDataVenda = new javax.swing.JFormattedTextField();
        jComboBoxCorretorResponsavel = new javax.swing.JComboBox<>();
        CadastroCorretorCT = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNameCT = new javax.swing.JTextField();
        jTextFieldNumberCT = new javax.swing.JTextField();
        jTextFieldSalCT = new javax.swing.JTextField();
        jTextField1DataCT = new javax.swing.JFormattedTextField();
        jButtonCancela2 = new javax.swing.JButton();
        jButtonConfirma2 = new javax.swing.JButton();
        CadastroCorretorCM = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButtonCancela3 = new javax.swing.JButton();
        jButtonConfirma3 = new javax.swing.JButton();
        jTextFieldNameCM = new javax.swing.JTextField();
        jTextFieldNumberCM = new javax.swing.JTextField();
        jComboBoxComissao = new javax.swing.JComboBox<>();
        CalculaSalario = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxCorretores = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldMes = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldAno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSalario = new javax.swing.JTextArea();
        AlteraSalario = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxCorretoresCT = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldNewPayment = new javax.swing.JTextField();
        jButtonCancela4 = new javax.swing.JButton();
        jButtonConfirma4 = new javax.swing.JButton();
        AlteraComissao = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxCorretoresCM = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jComboBoxNewComission = new javax.swing.JComboBox<>();
        jButtonCancela5 = new javax.swing.JButton();
        jButtonConfirma5 = new javax.swing.JButton();
        FaturamentoImobiliaria = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaFaturamentoImobiliaria = new javax.swing.JTextArea();
        LucroImobiliaria = new javax.swing.JPanel();
        ImovelVendido = new javax.swing.JPanel();
        ImovelEncalhado = new javax.swing.JPanel();
        FaturamentoCorretor = new javax.swing.JPanel();
        PagamentoCorretor = new javax.swing.JPanel();
        CorretorDoMes = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuBusca = new javax.swing.JMenu();
        jMenuBuscaImovel = new javax.swing.JMenuItem();
        jMenuCadastroImovel = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuCadastroVenda = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuCadastroCorretorCT = new javax.swing.JMenuItem();
        jMenuCadastroCorretorCM = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuCalculaSal = new javax.swing.JMenuItem();
        jMenuAltSal = new javax.swing.JMenuItem();
        jMenuAltCom = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuFaturamentoImobiliaria = new javax.swing.JMenuItem();
        jMenuLucroImobiliaria = new javax.swing.JMenuItem();
        jMenuImovelVendido = new javax.swing.JMenuItem();
        jMenuImovelEncalhado = new javax.swing.JMenuItem();
        jMenuFaturamentoCorretor = new javax.swing.JMenuItem();
        jMenuPagamentoCorretor = new javax.swing.JMenuItem();
        jMenuCorretorDoMes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TelaPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout TelaDefaultLayout = new javax.swing.GroupLayout(TelaDefault);
        TelaDefault.setLayout(TelaDefaultLayout);
        TelaDefaultLayout.setHorizontalGroup(
            TelaDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        TelaDefaultLayout.setVerticalGroup(
            TelaDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        TelaPrincipal.add(TelaDefault, "TelaDefault");

        jLabel21.setText("Tipo:");

        jLabel22.setText("Código:");

        jLabel23.setText("Descrição:");

        jLabel24.setText("Nome Proprietário:");

        jLabel25.setText("Valor:");

        jButtonCadastraImovel.setText("Cadastrar");
        jButtonCadastraImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraImovelActionPerformed(evt);
            }
        });

        jButton2.setText("Cancela");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel26.setText("Data:");

        try {
            jFormattedTextFieldData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jComboBoxTipoImovel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Apartamento", "Sala comercial", "Lote", "Chácara", "Sítio", "Fazenda" }));

        javax.swing.GroupLayout CadastroImovelLayout = new javax.swing.GroupLayout(CadastroImovel);
        CadastroImovel.setLayout(CadastroImovelLayout);
        CadastroImovelLayout.setHorizontalGroup(
            CadastroImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroImovelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroImovelLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipoImovel, 0, 535, Short.MAX_VALUE))
                    .addGroup(CadastroImovelLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodigo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroImovelLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDescricao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroImovelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCadastraImovel)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(CadastroImovelLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeProprietario))
                    .addGroup(CadastroImovelLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValor))
                    .addGroup(CadastroImovelLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldData)))
                .addContainerGap())
        );

        CadastroImovelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel21, jLabel22, jLabel23, jLabel24, jLabel25, jLabel26});

        CadastroImovelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, jButtonCadastraImovel});

        CadastroImovelLayout.setVerticalGroup(
            CadastroImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroImovelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipoImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(CadastroImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextFieldNomeProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(CadastroImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButtonCadastraImovel))
                .addContainerGap())
        );

        TelaPrincipal.add(CadastroImovel, "TelaCadastroImovel");

        jComboBoxTipoImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoImoveisActionPerformed(evt);
            }
        });

        jTableImóveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Código", "Descrição", "Proprietário", "Valor", "Data do Cadastro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableImóveis);

        jButtonExcluiImovel.setText("Excluir");
        jButtonExcluiImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluiImovelActionPerformed(evt);
            }
        });

        jButtonEditaImovel.setText("Editar");
        jButtonEditaImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditaImovelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuscaImovelLayout = new javax.swing.GroupLayout(BuscaImovel);
        BuscaImovel.setLayout(BuscaImovelLayout);
        BuscaImovelLayout.setHorizontalGroup(
            BuscaImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaImovelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscaImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addGroup(BuscaImovelLayout.createSequentialGroup()
                        .addComponent(jComboBoxTipoImoveis, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditaImovel)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluiImovel)))
                .addContainerGap())
        );

        BuscaImovelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonEditaImovel, jButtonExcluiImovel});

        BuscaImovelLayout.setVerticalGroup(
            BuscaImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscaImovelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscaImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipoImoveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluiImovel)
                    .addComponent(jButtonEditaImovel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );

        TelaPrincipal.add(BuscaImovel, "TelaBusca");

        jLabel1.setText("Código do Imóvel:");

        jLabel2.setText("Valor da Venda:");

        jLabel3.setText("Nome do Comprador:");

        jLabel4.setText("Data:");

        jLabel5.setText("Corretor Responsável:");

        jButtonConfirma1.setText("Confirma");
        jButtonConfirma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirma1ActionPerformed(evt);
            }
        });

        jButtonCancela1.setText("Cancela");
        jButtonCancela1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancela1ActionPerformed(evt);
            }
        });

        try {
            jTextFieldDataVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout CadastroVendaLayout = new javax.swing.GroupLayout(CadastroVenda);
        CadastroVenda.setLayout(CadastroVendaLayout);
        CadastroVendaLayout.setHorizontalGroup(
            CadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroVendaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodImovel))
                    .addGroup(CadastroVendaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCorretorResponsavel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CadastroVendaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorVenda))
                    .addGroup(CadastroVendaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeComprador))
                    .addGroup(CadastroVendaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDataVenda))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroVendaLayout.createSequentialGroup()
                        .addGap(0, 466, Short.MAX_VALUE)
                        .addComponent(jButtonConfirma1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancela1)))
                .addContainerGap())
        );

        CadastroVendaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        CadastroVendaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancela1, jButtonConfirma1});

        CadastroVendaLayout.setVerticalGroup(
            CadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCodImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNomeComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxCorretorResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addGroup(CadastroVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirma1)
                    .addComponent(jButtonCancela1))
                .addContainerGap())
        );

        TelaPrincipal.add(CadastroVenda, "TelaCadastroVenda");

        jLabel7.setText("Nome:");

        jLabel8.setText("Nº CRECI:");

        jLabel9.setText("Salário Fixo:");

        jLabel10.setText("Data de Admissão:");

        jTextFieldSalCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalCTActionPerformed(evt);
            }
        });

        try {
            jTextField1DataCT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButtonCancela2.setText("Cancela");
        jButtonCancela2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancela2ActionPerformed(evt);
            }
        });

        jButtonConfirma2.setText("Confirma");
        jButtonConfirma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirma2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CadastroCorretorCTLayout = new javax.swing.GroupLayout(CadastroCorretorCT);
        CadastroCorretorCT.setLayout(CadastroCorretorCTLayout);
        CadastroCorretorCTLayout.setHorizontalGroup(
            CadastroCorretorCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroCorretorCTLayout.createSequentialGroup()
                .addGroup(CadastroCorretorCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroCorretorCTLayout.createSequentialGroup()
                        .addContainerGap(472, Short.MAX_VALUE)
                        .addComponent(jButtonConfirma2)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancela2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CadastroCorretorCTLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CadastroCorretorCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastroCorretorCTLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1DataCT))
                            .addGroup(CadastroCorretorCTLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNameCT, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
                            .addGroup(CadastroCorretorCTLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNumberCT, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
                            .addGroup(CadastroCorretorCTLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSalCT, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        CadastroCorretorCTLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel7, jLabel8, jLabel9});

        CadastroCorretorCTLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancela2, jButtonConfirma2});

        CadastroCorretorCTLayout.setVerticalGroup(
            CadastroCorretorCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroCorretorCTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroCorretorCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldNameCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroCorretorCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldNumberCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroCorretorCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldSalCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroCorretorCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField1DataCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addGroup(CadastroCorretorCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancela2)
                    .addComponent(jButtonConfirma2))
                .addContainerGap())
        );

        TelaPrincipal.add(CadastroCorretorCT, "TelaCadastroCT");

        jLabel11.setText("Nome:");

        jLabel12.setText("Nº CRECI");

        jLabel13.setText("Comissão (%) :");

        jButtonCancela3.setText("Cancela");
        jButtonCancela3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancela3ActionPerformed(evt);
            }
        });

        jButtonConfirma3.setText("Confirma");
        jButtonConfirma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirma3ActionPerformed(evt);
            }
        });

        jComboBoxComissao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        javax.swing.GroupLayout CadastroCorretorCMLayout = new javax.swing.GroupLayout(CadastroCorretorCM);
        CadastroCorretorCM.setLayout(CadastroCorretorCMLayout);
        CadastroCorretorCMLayout.setHorizontalGroup(
            CadastroCorretorCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroCorretorCMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroCorretorCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroCorretorCMLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonConfirma3)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancela3))
                    .addGroup(CadastroCorretorCMLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNameCM))
                    .addGroup(CadastroCorretorCMLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumberCM, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
                    .addGroup(CadastroCorretorCMLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        CadastroCorretorCMLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel12, jLabel13});

        CadastroCorretorCMLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancela3, jButtonConfirma3});

        CadastroCorretorCMLayout.setVerticalGroup(
            CadastroCorretorCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroCorretorCMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroCorretorCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldNameCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroCorretorCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldNumberCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroCorretorCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addGroup(CadastroCorretorCMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancela3)
                    .addComponent(jButtonConfirma3))
                .addContainerGap())
        );

        TelaPrincipal.add(CadastroCorretorCM, "TelaCadastroCM");

        jLabel14.setText("Corretores:");

        jComboBoxCorretores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCorretoresActionPerformed(evt);
            }
        });

        jLabel15.setText("Mês:");

        jLabel16.setText("Ano:");

        jTextAreaSalario.setColumns(20);
        jTextAreaSalario.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSalario);

        javax.swing.GroupLayout CalculaSalarioLayout = new javax.swing.GroupLayout(CalculaSalario);
        CalculaSalario.setLayout(CalculaSalarioLayout);
        CalculaSalarioLayout.setHorizontalGroup(
            CalculaSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculaSalarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CalculaSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addGroup(CalculaSalarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(253, 253, 253))
                    .addGroup(CalculaSalarioLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCorretores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CalculaSalarioLayout.setVerticalGroup(
            CalculaSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculaSalarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CalculaSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(CalculaSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCorretores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );

        TelaPrincipal.add(CalculaSalario, "TelaCalculaSalario");

        jLabel17.setText("Corretores:");

        jLabel18.setText("Novo Valor:");

        jButtonCancela4.setText("Cancela");
        jButtonCancela4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancela4ActionPerformed(evt);
            }
        });

        jButtonConfirma4.setText("Confirma");
        jButtonConfirma4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirma4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AlteraSalarioLayout = new javax.swing.GroupLayout(AlteraSalario);
        AlteraSalario.setLayout(AlteraSalarioLayout);
        AlteraSalarioLayout.setHorizontalGroup(
            AlteraSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlteraSalarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlteraSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlteraSalarioLayout.createSequentialGroup()
                        .addGap(0, 466, Short.MAX_VALUE)
                        .addComponent(jButtonConfirma4)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancela4))
                    .addGroup(AlteraSalarioLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCorretoresCT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AlteraSalarioLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNewPayment)))
                .addContainerGap())
        );

        AlteraSalarioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel17, jLabel18});

        AlteraSalarioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancela4, jButtonConfirma4});

        AlteraSalarioLayout.setVerticalGroup(
            AlteraSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlteraSalarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlteraSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBoxCorretoresCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AlteraSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldNewPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                .addGroup(AlteraSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancela4)
                    .addComponent(jButtonConfirma4))
                .addContainerGap())
        );

        TelaPrincipal.add(AlteraSalario, "TelaAlteraSalario");

        jLabel19.setText("Corretores:");

        jComboBoxCorretoresCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCorretoresCMActionPerformed(evt);
            }
        });

        jLabel20.setText("Comissao (%):");

        jComboBoxNewComission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        jButtonCancela5.setText("Cancela");
        jButtonCancela5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancela5ActionPerformed(evt);
            }
        });

        jButtonConfirma5.setText("Confirma");
        jButtonConfirma5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirma5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AlteraComissaoLayout = new javax.swing.GroupLayout(AlteraComissao);
        AlteraComissao.setLayout(AlteraComissaoLayout);
        AlteraComissaoLayout.setHorizontalGroup(
            AlteraComissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlteraComissaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlteraComissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlteraComissaoLayout.createSequentialGroup()
                        .addGroup(AlteraComissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AlteraComissaoLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCorretoresCM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlteraComissaoLayout.createSequentialGroup()
                                .addGap(0, 466, Short.MAX_VALUE)
                                .addComponent(jButtonConfirma5)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancela5)))
                        .addContainerGap())
                    .addGroup(AlteraComissaoLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxNewComission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        AlteraComissaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCancela5, jButtonConfirma5});

        AlteraComissaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel19, jLabel20});

        AlteraComissaoLayout.setVerticalGroup(
            AlteraComissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlteraComissaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlteraComissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jComboBoxCorretoresCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AlteraComissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jComboBoxNewComission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addGroup(AlteraComissaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancela5)
                    .addComponent(jButtonConfirma5))
                .addContainerGap())
        );

        TelaPrincipal.add(AlteraComissao, "TelaAlteraComissao");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Faturamento do Mês"));

        jTextAreaFaturamentoImobiliaria.setColumns(20);
        jTextAreaFaturamentoImobiliaria.setRows(5);
        jScrollPane2.setViewportView(jTextAreaFaturamentoImobiliaria);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout FaturamentoImobiliariaLayout = new javax.swing.GroupLayout(FaturamentoImobiliaria);
        FaturamentoImobiliaria.setLayout(FaturamentoImobiliariaLayout);
        FaturamentoImobiliariaLayout.setHorizontalGroup(
            FaturamentoImobiliariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FaturamentoImobiliariaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        FaturamentoImobiliariaLayout.setVerticalGroup(
            FaturamentoImobiliariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FaturamentoImobiliariaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TelaPrincipal.add(FaturamentoImobiliaria, "FaturamentoImobialiaria");

        javax.swing.GroupLayout LucroImobiliariaLayout = new javax.swing.GroupLayout(LucroImobiliaria);
        LucroImobiliaria.setLayout(LucroImobiliariaLayout);
        LucroImobiliariaLayout.setHorizontalGroup(
            LucroImobiliariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        LucroImobiliariaLayout.setVerticalGroup(
            LucroImobiliariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        TelaPrincipal.add(LucroImobiliaria, "LucroImobiliaria");

        javax.swing.GroupLayout ImovelVendidoLayout = new javax.swing.GroupLayout(ImovelVendido);
        ImovelVendido.setLayout(ImovelVendidoLayout);
        ImovelVendidoLayout.setHorizontalGroup(
            ImovelVendidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        ImovelVendidoLayout.setVerticalGroup(
            ImovelVendidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        TelaPrincipal.add(ImovelVendido, "ImovelVendido");

        javax.swing.GroupLayout ImovelEncalhadoLayout = new javax.swing.GroupLayout(ImovelEncalhado);
        ImovelEncalhado.setLayout(ImovelEncalhadoLayout);
        ImovelEncalhadoLayout.setHorizontalGroup(
            ImovelEncalhadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        ImovelEncalhadoLayout.setVerticalGroup(
            ImovelEncalhadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        TelaPrincipal.add(ImovelEncalhado, "ImovelEncalhado");

        javax.swing.GroupLayout FaturamentoCorretorLayout = new javax.swing.GroupLayout(FaturamentoCorretor);
        FaturamentoCorretor.setLayout(FaturamentoCorretorLayout);
        FaturamentoCorretorLayout.setHorizontalGroup(
            FaturamentoCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        FaturamentoCorretorLayout.setVerticalGroup(
            FaturamentoCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        TelaPrincipal.add(FaturamentoCorretor, "FaturamentoCorretor");

        javax.swing.GroupLayout PagamentoCorretorLayout = new javax.swing.GroupLayout(PagamentoCorretor);
        PagamentoCorretor.setLayout(PagamentoCorretorLayout);
        PagamentoCorretorLayout.setHorizontalGroup(
            PagamentoCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        PagamentoCorretorLayout.setVerticalGroup(
            PagamentoCorretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        TelaPrincipal.add(PagamentoCorretor, "PagamentoCorretor");

        javax.swing.GroupLayout CorretorDoMesLayout = new javax.swing.GroupLayout(CorretorDoMes);
        CorretorDoMes.setLayout(CorretorDoMesLayout);
        CorretorDoMesLayout.setHorizontalGroup(
            CorretorDoMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        CorretorDoMesLayout.setVerticalGroup(
            CorretorDoMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        TelaPrincipal.add(CorretorDoMes, "CorretorDoMes");

        jMenuBusca.setText("Imóveis");

        jMenuBuscaImovel.setText("Busca");
        jMenuBuscaImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscaImovelActionPerformed(evt);
            }
        });
        jMenuBusca.add(jMenuBuscaImovel);

        jMenuCadastroImovel.setText("Cadastro");
        jMenuCadastroImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroImovelActionPerformed(evt);
            }
        });
        jMenuBusca.add(jMenuCadastroImovel);

        jMenuBar1.add(jMenuBusca);

        jMenu2.setText("Vendas");

        jMenuCadastroVenda.setText("Cadastro");
        jMenuCadastroVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroVendaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuCadastroVenda);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Corretores");

        jMenu1.setText("Cadastro");

        jMenuCadastroCorretorCT.setText("Contratado");
        jMenuCadastroCorretorCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroCorretorCTActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastroCorretorCT);

        jMenuCadastroCorretorCM.setText("Comissionado");
        jMenuCadastroCorretorCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroCorretorCMActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastroCorretorCM);

        jMenu3.add(jMenu1);

        jMenu5.setText("Salarios / Comissões");

        jMenuCalculaSal.setText("Calcular");
        jMenuCalculaSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCalculaSalActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuCalculaSal);

        jMenuAltSal.setText("Alterar Salário");
        jMenuAltSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAltSalActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuAltSal);

        jMenuAltCom.setText("Alterar Comissão");
        jMenuAltCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAltComActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuAltCom);

        jMenu3.add(jMenu5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Outros");

        jMenu6.setText("Relatórios");

        jMenuFaturamentoImobiliaria.setText("Faturamento Imobiliária");
        jMenuFaturamentoImobiliaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFaturamentoImobiliariaActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuFaturamentoImobiliaria);

        jMenuLucroImobiliaria.setText("Lucro Imobiliária");
        jMenuLucroImobiliaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLucroImobiliariaActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuLucroImobiliaria);

        jMenuImovelVendido.setText("Imóveis Vendidos");
        jMenuImovelVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuImovelVendidoActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuImovelVendido);

        jMenuImovelEncalhado.setText("Imóveis Encalhados");
        jMenuImovelEncalhado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuImovelEncalhadoActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuImovelEncalhado);

        jMenuFaturamentoCorretor.setText("Faturamento Corretor");
        jMenuFaturamentoCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFaturamentoCorretorActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuFaturamentoCorretor);

        jMenuPagamentoCorretor.setText("Pagamento Corretor");
        jMenuPagamentoCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPagamentoCorretorActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuPagamentoCorretor);

        jMenuCorretorDoMes.setText("Corretor do Mês");
        jMenuCorretorDoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCorretorDoMesActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuCorretorDoMes);

        jMenu4.add(jMenu6);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(676, 474));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadastroVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroVendaActionPerformed
        // TODO add your handling code here:
        jTextFieldCodImovel.setText("");
        jTextFieldNomeComprador.setText("");
        jTextFieldValorVenda.setText("");
        jTextFieldDataVenda.setText("");

        String[] listaCorretores = new String[corretores.size()];
        int idx = 0;

        for (Corretor c : corretores) {
            listaCorretores[idx] = c.getNome();
            idx++;

        }

        jComboBoxCorretorResponsavel.setModel(new javax.swing.DefaultComboBoxModel<>(listaCorretores));
        jComboBoxCorretorResponsavel.setSelectedIndex(0);

        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal, "TelaCadastroVenda");
    }//GEN-LAST:event_jMenuCadastroVendaActionPerformed

    private void jMenuCadastroImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroImovelActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal, "TelaCadastroImovel");
    }//GEN-LAST:event_jMenuCadastroImovelActionPerformed

    private void jMenuBuscaImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscaImovelActionPerformed
        // TODO add your handling code here:

        ArrayList<String> imoveisTipos = new ArrayList<String>();

        for (Imovel i : imoveis) {

            boolean testa_tipo = false;

            for (int idx = 0; idx < imoveisTipos.size(); idx++) {

                String tipo = (String) imoveisTipos.get(idx);

                if (tipo.equalsIgnoreCase(i.getTipo())) {
                    testa_tipo = true;
                    break;
                } else {
                    testa_tipo = false;
                }
            }

            if (testa_tipo == false) {
                imoveisTipos.add(i.getTipo());
            }

        }

        String[] types = new String[imoveisTipos.size() + 1];
        types[0] = "ESCOLHA UM TIPO";

        int cont = 1;
        for (String s : imoveisTipos) {
            types[cont] = s;
            cont++;
        }

        jComboBoxTipoImoveis.setModel(new javax.swing.DefaultComboBoxModel<>(types));
        jComboBoxTipoImoveis.setSelectedIndex(0);

        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal, "TelaBusca");
    }//GEN-LAST:event_jMenuBuscaImovelActionPerformed

    private void jButtonConfirma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirma1ActionPerformed
        // TODO add your handling code here:

        if (jTextFieldCodImovel.getText().equalsIgnoreCase("") || jTextFieldValorVenda.getText().equalsIgnoreCase("")
                || jTextFieldNomeComprador.getText().equalsIgnoreCase("") || jTextFieldDataVenda.getText().equalsIgnoreCase("  /  /    ")) {

            JOptionPane.showMessageDialog(this, "Algum campo não foi preenchido corretamente");

            jTextFieldCodImovel.setText("");
            jTextFieldValorVenda.setText("");
            jTextFieldNomeComprador.setText("");
            jTextFieldDataVenda.setText("");
            jComboBoxCorretorResponsavel.setSelectedIndex(0);

        } else {

            String cod = jTextFieldCodImovel.getText();
            float valor = Float.parseFloat(jTextFieldValorVenda.getText());
            String nomeComprador = jTextFieldNomeComprador.getText();
            String data = jTextFieldDataVenda.getText();
            String corretor = jComboBoxCorretorResponsavel.getItemAt(jComboBoxCorretorResponsavel.getSelectedIndex());

            try {
                objPrincipal.cadVenda(cod, valor, nomeComprador, data, corretor);
                JOptionPane.showMessageDialog(this, "Venda cadastrada com sucesso!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
            }

            jTextFieldCodImovel.setText("");
            jTextFieldValorVenda.setText("");
            jTextFieldNomeComprador.setText("");
            jTextFieldDataVenda.setText("");
            jComboBoxCorretorResponsavel.setSelectedIndex(0);
        }

        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal, "TelaCadastroVenda");
    }//GEN-LAST:event_jButtonConfirma1ActionPerformed

    private void jButtonCancela1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancela1ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal, "TelaDefault");
    }//GEN-LAST:event_jButtonCancela1ActionPerformed

    private void jTextFieldSalCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalCTActionPerformed

    private void jButtonConfirma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirma2ActionPerformed
        // TODO add your handling code here:
        String nameCT = jTextFieldNameCT.getText();
        String nCreciCT = jTextFieldNumberCT.getText();
        float salarioCT = Float.parseFloat(jTextFieldSalCT.getText());
        String dataCT = jTextField1DataCT.getText();

        try {
            objPrincipal.cadCorretorCT(nameCT, nCreciCT, salarioCT, dataCT);
            JOptionPane.showMessageDialog(this, "Corretor contratado cadastrado com sucesso!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

        jTextFieldNameCT.setText("");
        jTextFieldNumberCT.setText("");
        jTextFieldSalCT.setText("");
        jTextField1DataCT.setText("");

        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal, "TelaCadastroCT");
    }//GEN-LAST:event_jButtonConfirma2ActionPerformed

    private void jButtonCancela2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancela2ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal, "TelaDefault");
    }//GEN-LAST:event_jButtonCancela2ActionPerformed

    private void jButtonCancela3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancela3ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal, "TelaDefault");
    }//GEN-LAST:event_jButtonCancela3ActionPerformed

    private void jButtonConfirma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirma3ActionPerformed
        // TODO add your handling code here:
        String nameCM = jTextFieldNameCM.getText();
        String nCreciCM = jTextFieldNumberCM.getText();
        float comissionCM = (float) (1 + (jComboBoxComissao.getSelectedIndex())) / 100;

        try {
            objPrincipal.cadCorretorCM(nameCM, nCreciCM, comissionCM);
            JOptionPane.showMessageDialog(this, "Corretor comissionado cadastrado com sucesso!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

        jTextFieldNameCM.setText("");
        jTextFieldNumberCM.setText("");
        jComboBoxComissao.setSelectedIndex(0);

        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal, "TelaCadastroCM");
    }//GEN-LAST:event_jButtonConfirma3ActionPerformed

    private void jMenuCadastroCorretorCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroCorretorCTActionPerformed
        // TODO add your handling code here:
        jTextFieldNameCT.setText("");
        jTextFieldNumberCT.setText("");
        jTextFieldSalCT.setText("");
        jTextField1DataCT.setText("");

        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal, "TelaCadastroCT");
    }//GEN-LAST:event_jMenuCadastroCorretorCTActionPerformed

    private void jMenuCadastroCorretorCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroCorretorCMActionPerformed
        // TODO add your handling code here:
        jTextFieldNameCM.setText("");
        jTextFieldNumberCM.setText("");
        jComboBoxComissao.setSelectedIndex(0);

        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal, "TelaCadastroCM");
    }//GEN-LAST:event_jMenuCadastroCorretorCMActionPerformed

    private void jMenuAltSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAltSalActionPerformed
        // TODO add your handling code here:
        jTextFieldNewPayment.setText("");

        ArrayList<Contratado> contratados = new ArrayList<Contratado>();
        int idx = 0;

        for (Corretor c : corretores) {

            if (c instanceof Contratado) {
                contratados.add((Contratado) c);
            }

        }

        String[] listaCorretores = new String[contratados.size()];

        for (Contratado ct : contratados) {
            listaCorretores[idx] = ct.getNome();
            idx++;

        }

        jComboBoxCorretoresCT.setModel(new javax.swing.DefaultComboBoxModel<>(listaCorretores));
        jComboBoxCorretoresCT.setSelectedIndex(0);

        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal, "TelaAlteraSalario");
    }//GEN-LAST:event_jMenuAltSalActionPerformed

    private void jComboBoxCorretoresCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCorretoresCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCorretoresCMActionPerformed

    private void jMenuCalculaSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCalculaSalActionPerformed
        // TODO add your handling code here:
        jTextAreaSalario.setText("");
        jTextFieldMes.setText("");
        jTextFieldAno.setText("");

        String[] listaCorretores = new String[corretores.size() + 1];
        listaCorretores[0] = "SELECIONE UM CORRETOR";
        int idx = 1;

        for (Corretor c : corretores) {
            listaCorretores[idx] = c.getNome();
            idx++;

        }
        jComboBoxCorretores.setModel(new javax.swing.DefaultComboBoxModel<>(listaCorretores));
        jComboBoxCorretores.setSelectedIndex(0);

        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal, "TelaCalculaSalario");
    }//GEN-LAST:event_jMenuCalculaSalActionPerformed

    private void jMenuAltComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAltComActionPerformed
        // TODO add your handling code here:
        jComboBoxNewComission.setSelectedIndex(0);

        ArrayList<Comissionado> comissionados = new ArrayList<Comissionado>();

        int idx = 0;

        for (Corretor c : corretores) {

            if (c instanceof Comissionado) {
                comissionados.add((Comissionado) c);
            }

        }

        String[] listaCorretores = new String[comissionados.size()];

        for (Comissionado ct : comissionados) {
            listaCorretores[idx] = ct.getNome();
            idx++;

        }

        jComboBoxCorretoresCM.setModel(new javax.swing.DefaultComboBoxModel<>(listaCorretores));
        jComboBoxCorretoresCM.setSelectedIndex(0);

        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal, "TelaAlteraComissao");
    }//GEN-LAST:event_jMenuAltComActionPerformed

    private void jButtonConfirma4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirma4ActionPerformed
        // TODO add your handling code here:

        if (jTextFieldNewPayment.getText().equalsIgnoreCase("") || jTextFieldNewPayment.getText().equalsIgnoreCase("Error campo novo salário vazio!")
                || jTextFieldNewPayment.getText().equalsIgnoreCase("Salario alterado com sucesso!")) {
            jTextFieldNewPayment.setText("Error campo novo salário vazio!");
            jComboBoxCorretoresCT.setSelectedIndex(0);
        } else {
            String corretor = jComboBoxCorretoresCT.getItemAt(jComboBoxCorretoresCT.getSelectedIndex());
            float novo_salario = Float.parseFloat(jTextFieldNewPayment.getText());

            Corretor cor = objPrincipal.buscaCorretor(corretor);

            ((Contratado) cor).setSalarioFixo(novo_salario);

            try {
                objPrincipal.getObjACtrCorretor().serializaCorretor();
            } catch (Exception ex) {

            }
            jTextFieldNewPayment.setText("Salario alterado com sucesso!");
        }


    }//GEN-LAST:event_jButtonConfirma4ActionPerformed

    private void jButtonCancela4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancela4ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal, "TelaDefault");
    }//GEN-LAST:event_jButtonCancela4ActionPerformed

    private void jButtonConfirma5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirma5ActionPerformed
        // TODO add your handling code here:
        String corretor = jComboBoxCorretoresCM.getItemAt(jComboBoxCorretoresCM.getSelectedIndex());
        float nova_comissao = (float) (jComboBoxNewComission.getSelectedIndex() + 1) / 100;

        Corretor cor = objPrincipal.buscaCorretor(corretor);

        ((Comissionado) cor).setPercentualVenda(nova_comissao);

        try {
            objPrincipal.getObjACtrCorretor().serializaCorretor();
        } catch (Exception ex) {

        }

        JOptionPane.showMessageDialog(this, "Comissão alterado com sucesso");
    }//GEN-LAST:event_jButtonConfirma5ActionPerformed

    private void jMenuLucroImobiliariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLucroImobiliariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLucroImobiliariaActionPerformed

    private void jMenuImovelVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuImovelVendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuImovelVendidoActionPerformed

    private void jMenuFaturamentoImobiliariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFaturamentoImobiliariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuFaturamentoImobiliariaActionPerformed

    private void jMenuImovelEncalhadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuImovelEncalhadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuImovelEncalhadoActionPerformed

    private void jMenuFaturamentoCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFaturamentoCorretorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuFaturamentoCorretorActionPerformed

    private void jMenuPagamentoCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPagamentoCorretorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuPagamentoCorretorActionPerformed

    private void jMenuCorretorDoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCorretorDoMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCorretorDoMesActionPerformed

    private void jButtonCadastraImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraImovelActionPerformed

        if (jTextFieldCodigo.getText().equalsIgnoreCase("") || jTextFieldDescricao.getText().equalsIgnoreCase("")
                || jTextFieldDescricao.getText().equalsIgnoreCase("") || jTextFieldNomeProprietario.getText().equalsIgnoreCase("")
                || jTextFieldValor.getText().equalsIgnoreCase("") || jFormattedTextFieldData.getText().equalsIgnoreCase("")) {

            JOptionPane.showMessageDialog(this, "Algum campo não foi preenchido corretamente!");

            jTextFieldCodigo.setText("");
            jComboBoxTipoImovel.setSelectedIndex(0);
            jTextFieldDescricao.setText("");
            jTextFieldNomeProprietario.setText("");
            jTextFieldValor.setText("");
            jFormattedTextFieldData.setText("");

        } else {

            String nCodigo = jTextFieldCodigo.getText();
            String nTipo = jComboBoxTipoImovel.getItemAt(jComboBoxTipoImovel.getSelectedIndex());
            String nDescricao = jTextFieldDescricao.getText();
            String nNomeProp = jTextFieldNomeProprietario.getText();
            float nValor = Float.parseFloat(jTextFieldValor.getText());
            String nData = jFormattedTextFieldData.getText();

            try {
                objPrincipal.cadImovel(nTipo, nCodigo, nDescricao, nNomeProp, nValor, nData);
                JOptionPane.showMessageDialog(this, "Imovel cadastrado com sucesso!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
            jTextFieldCodigo.setText("");
            jComboBoxTipoImovel.setSelectedIndex(0);
            jTextFieldDescricao.setText("");
            jTextFieldNomeProprietario.setText("");
            jTextFieldValor.setText("");
            jFormattedTextFieldData.setText("");

        }

        CardLayout voltaDefault = (CardLayout) TelaPrincipal.getLayout();
        voltaDefault.show(TelaPrincipal, "TelaCadastroImovel");

    }//GEN-LAST:event_jButtonCadastraImovelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxCorretoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCorretoresActionPerformed
        // TODO add your handling code here:
        if (jComboBoxCorretores.getSelectedIndex() == 0) {

        } else {
            String corretor = jComboBoxCorretores.getItemAt(jComboBoxCorretores.getSelectedIndex());
            String mes = jTextFieldMes.getText();
            String ano = jTextFieldAno.getText();

            if (validaDataSalario(mes, ano)) {
                Corretor cor = objPrincipal.buscaCorretor(corretor);
                float comissao = objPrincipal.calculaSalario(cor, mes, ano);

                if (cor instanceof Contratado) {
                    String dados = "       " + cor.getNome() + "\n"
                            + "\nSalário: R$" + ((Contratado) cor).getSalarioFixo()
                            + "\nComissao: R$" + comissao
                            + "\nSalario Final: R$" + (comissao + ((Contratado) cor).getSalarioFixo())
                            + "\n";

                    jTextAreaSalario.setText(dados);
                    jTextFieldMes.setText("");
                    jTextFieldAno.setText("");
                    jComboBoxCorretores.setSelectedIndex(0);

                } else if (cor instanceof Comissionado) {
                    String dados = "       " + cor.getNome() + "\n"
                            + "\nComissao: R$" + comissao
                            + "\n";

                    jTextAreaSalario.setText(dados);
                    jTextFieldMes.setText("");
                    jTextFieldAno.setText("");
                    jComboBoxCorretores.setSelectedIndex(0);
                }
            } else {

                CardLayout card = (CardLayout) TelaPrincipal.getLayout();
                card.show(TelaPrincipal, "TelaCalculaSalario");

                jTextAreaSalario.setText("O mes ou ano inseridos não são validos!");
                jTextFieldMes.setText("");
                jTextFieldAno.setText("");
                jComboBoxCorretores.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_jComboBoxCorretoresActionPerformed

    private void jButtonCancela5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancela5ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) TelaPrincipal.getLayout();
        card.show(TelaPrincipal, "TelaDefault");
    }//GEN-LAST:event_jButtonCancela5ActionPerformed

    private void jComboBoxTipoImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoImoveisActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableImoveis = (DefaultTableModel) jTableImóveis.getModel();
        tableImoveis.setNumRows(0);

        for (Imovel i : imoveis) {

            if (i.getTipo().equalsIgnoreCase(jComboBoxTipoImoveis.getItemAt(jComboBoxTipoImoveis.getSelectedIndex()))) {
                DateFormat formatDate = new SimpleDateFormat("dd/MM/yyyy");
                String data = formatDate.format(i.getDataCadastro());

                tableImoveis.addRow(new Object[]{
                    i.getTipo(),
                    i.getCodigo(),
                    i.getDescricao(),
                    i.getNomeProprietario(),
                    "R$" + i.getValorRequerido(),
                    data

                });
            }
        }
    }//GEN-LAST:event_jComboBoxTipoImoveisActionPerformed

    private void jButtonEditaImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditaImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditaImovelActionPerformed

    private void jButtonExcluiImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluiImovelActionPerformed
        // TODO add your handling code here:
        if (jTableImóveis.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Nenhum imovel foi selecionado!");
        } else {
            DefaultTableModel tableImoveis = (DefaultTableModel) jTableImóveis.getModel();
            tableImoveis.removeRow(jTableImóveis.getSelectedRow());
        }
    }//GEN-LAST:event_jButtonExcluiImovelActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AlteraComissao;
    private javax.swing.JPanel AlteraSalario;
    private javax.swing.JPanel BuscaImovel;
    private javax.swing.JPanel CadastroCorretorCM;
    private javax.swing.JPanel CadastroCorretorCT;
    private javax.swing.JPanel CadastroImovel;
    private javax.swing.JPanel CadastroVenda;
    private javax.swing.JPanel CalculaSalario;
    private javax.swing.JPanel CorretorDoMes;
    private javax.swing.JPanel FaturamentoCorretor;
    private javax.swing.JPanel FaturamentoImobiliaria;
    private javax.swing.JPanel ImovelEncalhado;
    private javax.swing.JPanel ImovelVendido;
    private javax.swing.JPanel LucroImobiliaria;
    private javax.swing.JPanel PagamentoCorretor;
    private javax.swing.JPanel TelaDefault;
    private javax.swing.JPanel TelaPrincipal;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCadastraImovel;
    private javax.swing.JButton jButtonCancela1;
    private javax.swing.JButton jButtonCancela2;
    private javax.swing.JButton jButtonCancela3;
    private javax.swing.JButton jButtonCancela4;
    private javax.swing.JButton jButtonCancela5;
    private javax.swing.JButton jButtonConfirma1;
    private javax.swing.JButton jButtonConfirma2;
    private javax.swing.JButton jButtonConfirma3;
    private javax.swing.JButton jButtonConfirma4;
    private javax.swing.JButton jButtonConfirma5;
    private javax.swing.JButton jButtonEditaImovel;
    private javax.swing.JButton jButtonExcluiImovel;
    private javax.swing.JComboBox<String> jComboBoxComissao;
    private javax.swing.JComboBox<String> jComboBoxCorretorResponsavel;
    private javax.swing.JComboBox<String> jComboBoxCorretores;
    private javax.swing.JComboBox<String> jComboBoxCorretoresCM;
    private javax.swing.JComboBox<String> jComboBoxCorretoresCT;
    private javax.swing.JComboBox<String> jComboBoxNewComission;
    private javax.swing.JComboBox<String> jComboBoxTipoImoveis;
    private javax.swing.JComboBox<String> jComboBoxTipoImovel;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuAltCom;
    private javax.swing.JMenuItem jMenuAltSal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBusca;
    private javax.swing.JMenuItem jMenuBuscaImovel;
    private javax.swing.JMenuItem jMenuCadastroCorretorCM;
    private javax.swing.JMenuItem jMenuCadastroCorretorCT;
    private javax.swing.JMenuItem jMenuCadastroImovel;
    private javax.swing.JMenuItem jMenuCadastroVenda;
    private javax.swing.JMenuItem jMenuCalculaSal;
    private javax.swing.JMenuItem jMenuCorretorDoMes;
    private javax.swing.JMenuItem jMenuFaturamentoCorretor;
    private javax.swing.JMenuItem jMenuFaturamentoImobiliaria;
    private javax.swing.JMenuItem jMenuImovelEncalhado;
    private javax.swing.JMenuItem jMenuImovelVendido;
    private javax.swing.JMenuItem jMenuLucroImobiliaria;
    private javax.swing.JMenuItem jMenuPagamentoCorretor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableImóveis;
    private javax.swing.JTextArea jTextAreaFaturamentoImobiliaria;
    private javax.swing.JTextArea jTextAreaSalario;
    private javax.swing.JFormattedTextField jTextField1DataCT;
    private javax.swing.JTextField jTextFieldAno;
    private javax.swing.JTextField jTextFieldCodImovel;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JFormattedTextField jTextFieldDataVenda;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldMes;
    private javax.swing.JTextField jTextFieldNameCM;
    private javax.swing.JTextField jTextFieldNameCT;
    private javax.swing.JTextField jTextFieldNewPayment;
    private javax.swing.JTextField jTextFieldNomeComprador;
    private javax.swing.JTextField jTextFieldNomeProprietario;
    private javax.swing.JTextField jTextFieldNumberCM;
    private javax.swing.JTextField jTextFieldNumberCT;
    private javax.swing.JTextField jTextFieldSalCT;
    private javax.swing.JTextField jTextFieldValor;
    private javax.swing.JTextField jTextFieldValorVenda;
    // End of variables declaration//GEN-END:variables
}
